image: microsoft/aspnetcore-build:latest
stages:
 - build
 - test 
job:  
  stage: build
  script: dotnet build Test.Pager.Core.sln

job: 
  stage: test
  script: dotnet test Test.Paging.PhysicalLevel.Core
