image: microsoft/aspnetcore-build:latest
stages:
 - build
 - test 

#build_all:  
#  stage: build
#  script: dotnet build Test.Pager.Core.sln

test_run: 
  stage: test
  script: dotnet test Test.Paging.Physical/Test.Paging.PhysicalLevel.Core.csproj
