image: microsoft/dotnet:2.1-sdk
stages:
 - unit_test 
 - integration_test 
 - durability
 - benchmark
 - publish
 - deploy


test_physical_debug: 
  stage: unit_test  
  script: 
     - dotnet test Test.Paging.Physical -c Debug 
     
test_physical_release: 
  stage: unit_test  
  script: 
     - export PATH="$PATH:/root/.dotnet/tools"
     - dotnet tool install --global coverlet.console     
     - dotnet tool install coveralls.net --tool-path ./tools
     - dotnet build Test.Paging.Physical -c Release
     - coverlet Test.Paging.Physical/bin/Release/netcoreapp2.0/ -t dotnet -a "test Test.Paging.Physical -c Release --no-build" --format opencover --output "coverage.xml" --exclude "[Test*]*"
     - echo "tools/csmacnz.Coveralls --opencover -i coverage.xml --repoToken $COVER_TOKEN --commitId $CI_COMMIT_SHA --commitBranch $CI_COMMIT_REF_NAME --commitMessage $CI_COMMIT_TITLE --jobId $CI_JOB_ID"
     - tools/csmacnz.Coveralls --opencover -i coverage.xml --repoToken $COVER_TOKEN --commitId "$CI_COMMIT_SHA" --commitBranch "$CI_COMMIT_REF_NAME" --commitMessage "$CI_COMMIT_TITLE" --jobId "$CI_JOB_ID"

test_logical_debug: 
  stage: unit_test  
  script: 
    - dotnet test Test.Paging.LogicalLevel -c Debug -r testResult/

test_logical_release: 
  stage: unit_test  
  script: 
     - export PATH="$PATH:/root/.dotnet/tools"
     - dotnet tool install --global coverlet.console     
     - dotnet build Test.Paging.LogicalLevel -c Release
     - dotnet tool install coveralls.net --tool-path ./tools
     - coverlet Test.Paging.LogicalLevel/bin/Release/netcoreapp2.0 -t dotnet -a "test Test.Paging.LogicalLevel  -c Release --no-build" --format opencover --output "coverage.xml"  --exclude "[Test*]*"
     - tools/csmacnz.Coveralls --opencover -i coverage.xml --repoToken $COVER_TOKEN --commitId "$CI_COMMIT_SHA" --commitBranch "$CI_COMMIT_REF_NAME" --commitMessage "$CI_COMMIT_TITLE" --jobId "$CI_JOB_ID"        

test_integration_physical_debug: 
  stage: integration_test  
  script: 
     - dotnet test Test.Integration.Physical/Test.Integration.Physical.csproj -c Debug -r testResult/ 

test_integration_physical_release: 
  stage: integration_test  
  script: 
    - dotnet test Test.Integration.Physical/Test.Integration.Physical.csproj -c Release -r testResult/


#durability_physical:
#   stage: durability
#   script:
#     - dotnet run --project Durability.Paging.PhysicalLevel/Durability.Paging.PhysicalLevel.Core.csproj -c Release

benchmark_physical:
  stage: benchmark  
  artifacts:
     paths:
     - Benchmarks
  script:
    - dotnet run --project Benchmark.Paging.PhysicalLevel/Benchmark.Paging.PhysicalLevel.csproj -c Release


benchmark_logical:
  stage: benchmark  
  artifacts:
     paths:
      - Benchmarks
  script:
    - dotnet run --project Benchmark.Paging.LogicalLevel/Benchmark.Paging.LogicalLevel.csproj -c Release


pages:
   stage: publish
   dependencies:
       - benchmark_logical
       - benchmark_physical      
   artifacts:
     paths: 
       - public
   only:
     - master
   script: 
    - cp -r Benchmarks public  
  #  - cp -r Benchmark.Paging.LogicalLevel/bin/Release/Benchmarks/* public/benchmarks/logical
    

packages_physical_release:
  stage: deploy
  only:
     - master
  script: 
   - dotnet build System.IO.Paging.PhysicalLevel/System.IO.Paging.PhysicalLevel.csproj -c Release 
   - dotnet nuget push System.IO.Paging.PhysicalLevel/bin/Release/*.nupkg -k oy2cqotpghuxh56wruoabzcnpnh7z3auxcbbc5y26tngtu -s https://api.nuget.org/v3/index.json

packages_physical_debug:
  stage: deploy
  only:
     - master
  script: 
   - dotnet build System.IO.Paging.PhysicalLevel/System.IO.Paging.PhysicalLevel.csproj -c Debug 
   - dotnet nuget push System.IO.Paging.PhysicalLevel/bin/Debug/*.nupkg -k oy2cqotpghuxh56wruoabzcnpnh7z3auxcbbc5y26tngtu -s https://api.nuget.org/v3/index.json
   
packages_logical_release:
  stage: deploy
  only:
     - master
  script: 
   - dotnet build System.IO.Paging.LogicalLevel/System.IO.Paging.LogicalLevel.csproj -c Release 
   - dotnet nuget push System.IO.Paging.LogicalLevel/bin/Release/*.nupkg -k oy2cqotpghuxh56wruoabzcnpnh7z3auxcbbc5y26tngtu -s https://api.nuget.org/v3/index.json
   
packages_logical_debug:
  stage: deploy
  only:
     - master
  script:    
   - dotnet build System.IO.Paging.LogicalLevel/System.IO.Paging.LogicalLevel.csproj -c Debug
   - dotnet nuget push System.IO.Paging.LogicalLevel/bin/Debug/*.nupkg -k oy2cqotpghuxh56wruoabzcnpnh7z3auxcbbc5y26tngtu -s https://api.nuget.org/v3/index.json

packages_stubs:
  stage: deploy
  script:    
   - dotnet build System.IO.Paging.PhysicalLevel.MemoryStubs/System.IO.Paging.PhysicalLevel.MemoryStubs.csproj -c Release 
   - dotnet nuget push System.IO.Paging.PhysicalLevel.MemoryStubs/bin/Release/*.nupkg -k oy2cqotpghuxh56wruoabzcnpnh7z3auxcbbc5y26tngtu -s https://api.nuget.org/v3/index.json
   